language: java
arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - sudo apt install ansible
script: 
  - export BUILD_TAG=`date +%Y%m%d`
  - docker build .  -t toyangdon/ansible-awx:$BUILD_TAG
  - docker push  toyangdon/ansible-awx:$BUILD_TAG
